// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoIqUm-rJ_pTGHMkPsRweamHMHxQADvzA',
    appId: '1:815579336789:web:909a1f0fdaff46cc6384dc',
    messagingSenderId: '815579336789',
    projectId: 'grocerylistapp-cd542',
    authDomain: 'grocerylistapp-cd542.firebaseapp.com',
    storageBucket: 'grocerylistapp-cd542.firebasestorage.app',
    measurementId: 'G-Y1XKW1NP9G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZfClwb0xoS7mffaFUpa_UwIMPOZH_Oo',
    appId: '1:815579336789:ios:3c61acdb84667b856384dc',
    messagingSenderId: '815579336789',
    projectId: 'grocerylistapp-cd542',
    storageBucket: 'grocerylistapp-cd542.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoIqUm-rJ_pTGHMkPsRweamHMHxQADvzA',
    appId: '1:815579336789:web:eb2a33157f64d0366384dc',
    messagingSenderId: '815579336789',
    projectId: 'grocerylistapp-cd542',
    authDomain: 'grocerylistapp-cd542.firebaseapp.com',
    storageBucket: 'grocerylistapp-cd542.firebasestorage.app',
    measurementId: 'G-WL8Z96JKSH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZfClwb0xoS7mffaFUpa_UwIMPOZH_Oo',
    appId: '1:815579336789:ios:3c61acdb84667b856384dc',
    messagingSenderId: '815579336789',
    projectId: 'grocerylistapp-cd542',
    storageBucket: 'grocerylistapp-cd542.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStM6tIMQR6d1BpNukJSKYml58WY-NwyE',
    appId: '1:815579336789:android:76708fd98301a9f76384dc',
    messagingSenderId: '815579336789',
    projectId: 'grocerylistapp-cd542',
    storageBucket: 'grocerylistapp-cd542.firebasestorage.app',
  );

}